// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
    id, event_type, result, actor_user_id, target_type, target_id,
    request_id, changed_fields, occurred_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9
)
`

type CreateAuditEventParams struct {
	ID            uuid.UUID          `db:"id"`
	EventType     string             `db:"event_type"`
	Result        string             `db:"result"`
	ActorUserID   *uuid.UUID         `db:"actor_user_id"`
	TargetType    *string            `db:"target_type"`
	TargetID      *uuid.UUID         `db:"target_id"`
	RequestID     *string            `db:"request_id"`
	ChangedFields []string           `db:"changed_fields"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.EventType,
		arg.Result,
		arg.ActorUserID,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.ChangedFields,
		arg.OccurredAt,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, event_type, result, actor_user_id, target_type, target_id, request_id, changed_fields, occurred_at
FROM audit_events
WHERE ($1::text = '' OR event_type = $1::text)
  AND (
        $2::timestamptz IS NULL
        OR (occurred_at, id) < ($2::timestamptz, $3::uuid)
      )
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListAuditEventsParams struct {
	EventType  string             `db:"event_type"`
	CursorTime pgtype.Timestamptz `db:"cursor_time"`
	CursorID   uuid.UUID          `db:"cursor_id"`
	PageLimit  int32              `db:"page_limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.EventType,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Result,
			&i.ActorUserID,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.ChangedFields,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
