// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :one
UPDATE authorization_codes
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, code_hash, auth_transaction_id, consent_grant_id, user_id, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, nonce_value, auth_time, created_at, expires_at, consumed_at
`

type ConsumeAuthorizationCodeParams struct {
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
	ID         uuid.UUID          `db:"id"`
}

func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, arg ConsumeAuthorizationCodeParams) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeAuthorizationCode, arg.ConsumedAt, arg.ID)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.AuthTransactionID,
		&i.ConsentGrantID,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.NonceValue,
		&i.AuthTime,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :exec
INSERT INTO authorization_codes (
    id, code_hash, auth_transaction_id, consent_grant_id, user_id, client_id,
    redirect_uri, scopes, pkce_challenge, pkce_method, nonce_value,
    auth_time, created_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14
)
`

type CreateAuthorizationCodeParams struct {
	ID                uuid.UUID          `db:"id"`
	CodeHash          []byte             `db:"code_hash"`
	AuthTransactionID uuid.UUID          `db:"auth_transaction_id"`
	ConsentGrantID    uuid.UUID          `db:"consent_grant_id"`
	UserID            uuid.UUID          `db:"user_id"`
	ClientID          uuid.UUID          `db:"client_id"`
	RedirectUri       string             `db:"redirect_uri"`
	Scopes            []string           `db:"scopes"`
	PkceChallenge     string             `db:"pkce_challenge"`
	PkceMethod        string             `db:"pkce_method"`
	NonceValue        *string            `db:"nonce_value"`
	AuthTime          pgtype.Timestamptz `db:"auth_time"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, createAuthorizationCode,
		arg.ID,
		arg.CodeHash,
		arg.AuthTransactionID,
		arg.ConsentGrantID,
		arg.UserID,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scopes,
		arg.PkceChallenge,
		arg.PkceMethod,
		arg.NonceValue,
		arg.AuthTime,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteRetiredAuthorizationCodes = `-- name: DeleteRetiredAuthorizationCodes :execrows
DELETE FROM authorization_codes
WHERE expires_at <= $1
  AND (consumed_at IS NOT NULL OR expires_at <= $1)
`

func (q *Queries) DeleteRetiredAuthorizationCodes(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredAuthorizationCodes, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorizationCodeByHash = `-- name: GetAuthorizationCodeByHash :one
SELECT id, code_hash, auth_transaction_id, consent_grant_id, user_id, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, nonce_value, auth_time, created_at, expires_at, consumed_at FROM authorization_codes WHERE code_hash = $1
`

func (q *Queries) GetAuthorizationCodeByHash(ctx context.Context, codeHash []byte) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeByHash, codeHash)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.AuthTransactionID,
		&i.ConsentGrantID,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.NonceValue,
		&i.AuthTime,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const lockAuthorizationCodeByHash = `-- name: LockAuthorizationCodeByHash :one
SELECT id, code_hash, auth_transaction_id, consent_grant_id, user_id, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, nonce_value, auth_time, created_at, expires_at, consumed_at FROM authorization_codes WHERE code_hash = $1 FOR UPDATE
`

func (q *Queries) LockAuthorizationCodeByHash(ctx context.Context, codeHash []byte) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, lockAuthorizationCodeByHash, codeHash)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.AuthTransactionID,
		&i.ConsentGrantID,
		&i.UserID,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.NonceValue,
		&i.AuthTime,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
