// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authflow.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAuthTransaction = `-- name: ConsumeAuthTransaction :one
UPDATE auth_transactions
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, token_hash, transaction_kind, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, state_value, nonce_value, prompt_create, created_at, expires_at, consumed_at, failure_reason, response_type, response_mode, prompt_values, max_age_seconds
`

type ConsumeAuthTransactionParams struct {
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
	ID         uuid.UUID          `db:"id"`
}

func (q *Queries) ConsumeAuthTransaction(ctx context.Context, arg ConsumeAuthTransactionParams) (AuthTransaction, error) {
	row := q.db.QueryRow(ctx, consumeAuthTransaction, arg.ConsumedAt, arg.ID)
	var i AuthTransaction
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TransactionKind,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.StateValue,
		&i.NonceValue,
		&i.PromptCreate,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FailureReason,
		&i.ResponseType,
		&i.ResponseMode,
		&i.PromptValues,
		&i.MaxAgeSeconds,
	)
	return i, err
}

const createAuthTransaction = `-- name: CreateAuthTransaction :exec
INSERT INTO auth_transactions (
    id, token_hash, transaction_kind, client_id, redirect_uri, scopes,
    pkce_challenge, pkce_method, state_value, nonce_value, prompt_create,
    response_type, response_mode, prompt_values, max_age_seconds,
    created_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16,
    $17
)
`

type CreateAuthTransactionParams struct {
	ID              uuid.UUID          `db:"id"`
	TokenHash       []byte             `db:"token_hash"`
	TransactionKind string             `db:"transaction_kind"`
	ClientID        *uuid.UUID         `db:"client_id"`
	RedirectUri     *string            `db:"redirect_uri"`
	Scopes          []string           `db:"scopes"`
	PkceChallenge   *string            `db:"pkce_challenge"`
	PkceMethod      *string            `db:"pkce_method"`
	StateValue      *string            `db:"state_value"`
	NonceValue      *string            `db:"nonce_value"`
	PromptCreate    bool               `db:"prompt_create"`
	ResponseType    *string            `db:"response_type"`
	ResponseMode    *string            `db:"response_mode"`
	PromptValues    []string           `db:"prompt_values"`
	MaxAgeSeconds   *int64             `db:"max_age_seconds"`
	CreatedAt       pgtype.Timestamptz `db:"created_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateAuthTransaction(ctx context.Context, arg CreateAuthTransactionParams) error {
	_, err := q.db.Exec(ctx, createAuthTransaction,
		arg.ID,
		arg.TokenHash,
		arg.TransactionKind,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scopes,
		arg.PkceChallenge,
		arg.PkceMethod,
		arg.StateValue,
		arg.NonceValue,
		arg.PromptCreate,
		arg.ResponseType,
		arg.ResponseMode,
		arg.PromptValues,
		arg.MaxAgeSeconds,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteRetiredAuthTransactions = `-- name: DeleteRetiredAuthTransactions :execrows
WITH candidates AS (
    SELECT transactions.id
    FROM auth_transactions AS transactions
    WHERE transactions.consumed_at IS NOT NULL
      AND transactions.consumed_at <= $1
      AND NOT EXISTS (
          SELECT 1 FROM preauth_sessions AS preauth
          WHERE preauth.auth_transaction_id = transactions.id
      )
      AND NOT EXISTS (
          SELECT 1 FROM authorization_codes AS codes
          WHERE codes.auth_transaction_id = transactions.id
      )
    ORDER BY transactions.consumed_at, transactions.id
    LIMIT $2
    FOR UPDATE OF transactions SKIP LOCKED
)
DELETE FROM auth_transactions AS transactions
USING candidates
WHERE transactions.id = candidates.id
`

type DeleteRetiredAuthTransactionsParams struct {
	Cutoff     pgtype.Timestamptz `db:"cutoff"`
	BatchLimit int32              `db:"batch_limit"`
}

func (q *Queries) DeleteRetiredAuthTransactions(ctx context.Context, arg DeleteRetiredAuthTransactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredAuthTransactions, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireAuthTransactions = `-- name: ExpireAuthTransactions :many
WITH candidates AS (
    SELECT id
    FROM auth_transactions
    WHERE consumed_at IS NULL AND expires_at <= $1
    ORDER BY expires_at, id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE auth_transactions AS transactions
SET consumed_at = $1, failure_reason = 'expired'
FROM candidates
WHERE transactions.id = candidates.id
RETURNING transactions.id
`

type ExpireAuthTransactionsParams struct {
	Now        pgtype.Timestamptz `db:"now"`
	BatchLimit int32              `db:"batch_limit"`
}

func (q *Queries) ExpireAuthTransactions(ctx context.Context, arg ExpireAuthTransactionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expireAuthTransactions, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthTransactionByID = `-- name: GetAuthTransactionByID :one
SELECT id, token_hash, transaction_kind, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, state_value, nonce_value, prompt_create, created_at, expires_at, consumed_at, failure_reason, response_type, response_mode, prompt_values, max_age_seconds FROM auth_transactions WHERE id = $1
`

func (q *Queries) GetAuthTransactionByID(ctx context.Context, id uuid.UUID) (AuthTransaction, error) {
	row := q.db.QueryRow(ctx, getAuthTransactionByID, id)
	var i AuthTransaction
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TransactionKind,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.StateValue,
		&i.NonceValue,
		&i.PromptCreate,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FailureReason,
		&i.ResponseType,
		&i.ResponseMode,
		&i.PromptValues,
		&i.MaxAgeSeconds,
	)
	return i, err
}

const getAuthTransactionByTokenHash = `-- name: GetAuthTransactionByTokenHash :one
SELECT id, token_hash, transaction_kind, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, state_value, nonce_value, prompt_create, created_at, expires_at, consumed_at, failure_reason, response_type, response_mode, prompt_values, max_age_seconds FROM auth_transactions WHERE token_hash = $1
`

func (q *Queries) GetAuthTransactionByTokenHash(ctx context.Context, tokenHash []byte) (AuthTransaction, error) {
	row := q.db.QueryRow(ctx, getAuthTransactionByTokenHash, tokenHash)
	var i AuthTransaction
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TransactionKind,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.StateValue,
		&i.NonceValue,
		&i.PromptCreate,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FailureReason,
		&i.ResponseType,
		&i.ResponseMode,
		&i.PromptValues,
		&i.MaxAgeSeconds,
	)
	return i, err
}

const lockAuthTransactionByID = `-- name: LockAuthTransactionByID :one
SELECT id, token_hash, transaction_kind, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, state_value, nonce_value, prompt_create, created_at, expires_at, consumed_at, failure_reason, response_type, response_mode, prompt_values, max_age_seconds FROM auth_transactions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAuthTransactionByID(ctx context.Context, id uuid.UUID) (AuthTransaction, error) {
	row := q.db.QueryRow(ctx, lockAuthTransactionByID, id)
	var i AuthTransaction
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TransactionKind,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.StateValue,
		&i.NonceValue,
		&i.PromptCreate,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FailureReason,
		&i.ResponseType,
		&i.ResponseMode,
		&i.PromptValues,
		&i.MaxAgeSeconds,
	)
	return i, err
}

const rejectAuthTransaction = `-- name: RejectAuthTransaction :one
UPDATE auth_transactions
SET consumed_at = $1, failure_reason = $2
WHERE id = $3
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id, token_hash, transaction_kind, client_id, redirect_uri, scopes, pkce_challenge, pkce_method, state_value, nonce_value, prompt_create, created_at, expires_at, consumed_at, failure_reason, response_type, response_mode, prompt_values, max_age_seconds
`

type RejectAuthTransactionParams struct {
	ConsumedAt    pgtype.Timestamptz `db:"consumed_at"`
	FailureReason *string            `db:"failure_reason"`
	ID            uuid.UUID          `db:"id"`
}

func (q *Queries) RejectAuthTransaction(ctx context.Context, arg RejectAuthTransactionParams) (AuthTransaction, error) {
	row := q.db.QueryRow(ctx, rejectAuthTransaction, arg.ConsumedAt, arg.FailureReason, arg.ID)
	var i AuthTransaction
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TransactionKind,
		&i.ClientID,
		&i.RedirectUri,
		&i.Scopes,
		&i.PkceChallenge,
		&i.PkceMethod,
		&i.StateValue,
		&i.NonceValue,
		&i.PromptCreate,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.FailureReason,
		&i.ResponseType,
		&i.ResponseMode,
		&i.PromptValues,
		&i.MaxAgeSeconds,
	)
	return i, err
}
