// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCClient = `-- name: CreateOIDCClient :one
INSERT INTO oidc_clients (
    id, client_id, client_type, token_endpoint_auth_method,
    name, description, logo_uri, status, registration_enabled,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
RETURNING id, client_id, client_type, token_endpoint_auth_method, name, description, logo_uri, status, registration_enabled, created_at, updated_at
`

type CreateOIDCClientParams struct {
	ID                      uuid.UUID          `db:"id"`
	ClientID                string             `db:"client_id"`
	ClientType              string             `db:"client_type"`
	TokenEndpointAuthMethod string             `db:"token_endpoint_auth_method"`
	Name                    string             `db:"name"`
	Description             string             `db:"description"`
	LogoUri                 *string            `db:"logo_uri"`
	Status                  string             `db:"status"`
	RegistrationEnabled     bool               `db:"registration_enabled"`
	CreatedAt               pgtype.Timestamptz `db:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) CreateOIDCClient(ctx context.Context, arg CreateOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, createOIDCClient,
		arg.ID,
		arg.ClientID,
		arg.ClientType,
		arg.TokenEndpointAuthMethod,
		arg.Name,
		arg.Description,
		arg.LogoUri,
		arg.Status,
		arg.RegistrationEnabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientType,
		&i.TokenEndpointAuthMethod,
		&i.Name,
		&i.Description,
		&i.LogoUri,
		&i.Status,
		&i.RegistrationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOIDCClientLogoutURI = `-- name: CreateOIDCClientLogoutURI :exec
INSERT INTO oidc_client_logout_uris (client_id, uri, created_at)
VALUES ($1, $2, $3)
`

type CreateOIDCClientLogoutURIParams struct {
	ClientID  uuid.UUID          `db:"client_id"`
	Uri       string             `db:"uri"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateOIDCClientLogoutURI(ctx context.Context, arg CreateOIDCClientLogoutURIParams) error {
	_, err := q.db.Exec(ctx, createOIDCClientLogoutURI, arg.ClientID, arg.Uri, arg.CreatedAt)
	return err
}

const createOIDCClientRedirectURI = `-- name: CreateOIDCClientRedirectURI :exec
INSERT INTO oidc_client_redirect_uris (client_id, uri, created_at)
VALUES ($1, $2, $3)
`

type CreateOIDCClientRedirectURIParams struct {
	ClientID  uuid.UUID          `db:"client_id"`
	Uri       string             `db:"uri"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateOIDCClientRedirectURI(ctx context.Context, arg CreateOIDCClientRedirectURIParams) error {
	_, err := q.db.Exec(ctx, createOIDCClientRedirectURI, arg.ClientID, arg.Uri, arg.CreatedAt)
	return err
}

const createOIDCClientScope = `-- name: CreateOIDCClientScope :exec
INSERT INTO oidc_client_scopes (client_id, scope, created_at)
VALUES ($1, $2, $3)
`

type CreateOIDCClientScopeParams struct {
	ClientID  uuid.UUID          `db:"client_id"`
	Scope     string             `db:"scope"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateOIDCClientScope(ctx context.Context, arg CreateOIDCClientScopeParams) error {
	_, err := q.db.Exec(ctx, createOIDCClientScope, arg.ClientID, arg.Scope, arg.CreatedAt)
	return err
}

const createOIDCClientSecret = `-- name: CreateOIDCClientSecret :exec
INSERT INTO oidc_client_secrets (
    id, client_id, secret_hash, version, created_at
) VALUES (
    $1, $2, $3, 1, $4
)
`

type CreateOIDCClientSecretParams struct {
	ID         uuid.UUID          `db:"id"`
	ClientID   uuid.UUID          `db:"client_id"`
	SecretHash []byte             `db:"secret_hash"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
}

func (q *Queries) CreateOIDCClientSecret(ctx context.Context, arg CreateOIDCClientSecretParams) error {
	_, err := q.db.Exec(ctx, createOIDCClientSecret,
		arg.ID,
		arg.ClientID,
		arg.SecretHash,
		arg.CreatedAt,
	)
	return err
}

const deleteOIDCClientLogoutURIs = `-- name: DeleteOIDCClientLogoutURIs :exec
DELETE FROM oidc_client_logout_uris WHERE client_id = $1
`

func (q *Queries) DeleteOIDCClientLogoutURIs(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCClientLogoutURIs, clientID)
	return err
}

const deleteOIDCClientRedirectURIs = `-- name: DeleteOIDCClientRedirectURIs :exec
DELETE FROM oidc_client_redirect_uris WHERE client_id = $1
`

func (q *Queries) DeleteOIDCClientRedirectURIs(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCClientRedirectURIs, clientID)
	return err
}

const deleteOIDCClientScopes = `-- name: DeleteOIDCClientScopes :exec
DELETE FROM oidc_client_scopes WHERE client_id = $1
`

func (q *Queries) DeleteOIDCClientScopes(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCClientScopes, clientID)
	return err
}

const getOIDCClientByClientID = `-- name: GetOIDCClientByClientID :one
SELECT id, client_id, client_type, token_endpoint_auth_method, name, description, logo_uri, status, registration_enabled, created_at, updated_at FROM oidc_clients WHERE client_id = $1
`

func (q *Queries) GetOIDCClientByClientID(ctx context.Context, clientID string) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClientByClientID, clientID)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientType,
		&i.TokenEndpointAuthMethod,
		&i.Name,
		&i.Description,
		&i.LogoUri,
		&i.Status,
		&i.RegistrationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOIDCClientByID = `-- name: GetOIDCClientByID :one
SELECT id, client_id, client_type, token_endpoint_auth_method, name, description, logo_uri, status, registration_enabled, created_at, updated_at FROM oidc_clients WHERE id = $1
`

func (q *Queries) GetOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error) {
	row := q.db.QueryRow(ctx, getOIDCClientByID, id)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientType,
		&i.TokenEndpointAuthMethod,
		&i.Name,
		&i.Description,
		&i.LogoUri,
		&i.Status,
		&i.RegistrationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveOIDCClientSecretHashes = `-- name: ListActiveOIDCClientSecretHashes :many
SELECT secret_hash
FROM oidc_client_secrets
WHERE client_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveOIDCClientSecretHashes(ctx context.Context, clientID uuid.UUID) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listActiveOIDCClientSecretHashes, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := [][]byte{}
	for rows.Next() {
		var secret_hash []byte
		if err := rows.Scan(&secret_hash); err != nil {
			return nil, err
		}
		items = append(items, secret_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientLogoutURIs = `-- name: ListOIDCClientLogoutURIs :many
SELECT uri FROM oidc_client_logout_uris
WHERE client_id = $1
ORDER BY uri
`

func (q *Queries) ListOIDCClientLogoutURIs(ctx context.Context, clientID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOIDCClientLogoutURIs, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var uri string
		if err := rows.Scan(&uri); err != nil {
			return nil, err
		}
		items = append(items, uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientRedirectURIs = `-- name: ListOIDCClientRedirectURIs :many
SELECT uri FROM oidc_client_redirect_uris
WHERE client_id = $1
ORDER BY uri
`

func (q *Queries) ListOIDCClientRedirectURIs(ctx context.Context, clientID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOIDCClientRedirectURIs, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var uri string
		if err := rows.Scan(&uri); err != nil {
			return nil, err
		}
		items = append(items, uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClientScopes = `-- name: ListOIDCClientScopes :many
SELECT scope FROM oidc_client_scopes
WHERE client_id = $1
ORDER BY scope
`

func (q *Queries) ListOIDCClientScopes(ctx context.Context, clientID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOIDCClientScopes, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var scope string
		if err := rows.Scan(&scope); err != nil {
			return nil, err
		}
		items = append(items, scope)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCClients = `-- name: ListOIDCClients :many
SELECT id, client_id, client_type, token_endpoint_auth_method, name, description, logo_uri, status, registration_enabled, created_at, updated_at
FROM oidc_clients
WHERE (
        $1::timestamptz IS NULL
        OR (created_at, id) < ($1::timestamptz, $2::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListOIDCClientsParams struct {
	CursorTime pgtype.Timestamptz `db:"cursor_time"`
	CursorID   uuid.UUID          `db:"cursor_id"`
	PageLimit  int32              `db:"page_limit"`
}

func (q *Queries) ListOIDCClients(ctx context.Context, arg ListOIDCClientsParams) ([]OidcClient, error) {
	rows, err := q.db.Query(ctx, listOIDCClients, arg.CursorTime, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClient{}
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientType,
			&i.TokenEndpointAuthMethod,
			&i.Name,
			&i.Description,
			&i.LogoUri,
			&i.Status,
			&i.RegistrationEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOIDCClientByID = `-- name: LockOIDCClientByID :one
SELECT id, client_id, client_type, token_endpoint_auth_method, name, description, logo_uri, status, registration_enabled, created_at, updated_at FROM oidc_clients WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error) {
	row := q.db.QueryRow(ctx, lockOIDCClientByID, id)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientType,
		&i.TokenEndpointAuthMethod,
		&i.Name,
		&i.Description,
		&i.LogoUri,
		&i.Status,
		&i.RegistrationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeActiveOIDCClientSecrets = `-- name: RevokeActiveOIDCClientSecrets :many
UPDATE oidc_client_secrets
SET revoked_at = $1
WHERE client_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeActiveOIDCClientSecretsParams struct {
	RevokedAt pgtype.Timestamptz `db:"revoked_at"`
	ClientID  uuid.UUID          `db:"client_id"`
}

func (q *Queries) RevokeActiveOIDCClientSecrets(ctx context.Context, arg RevokeActiveOIDCClientSecretsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeActiveOIDCClientSecrets, arg.RevokedAt, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCClient = `-- name: UpdateOIDCClient :one
UPDATE oidc_clients SET
    name = $1,
    description = $2,
    logo_uri = $3,
    status = $4,
    registration_enabled = $5,
    updated_at = $6
WHERE id = $7 AND updated_at = $8
RETURNING id, client_id, client_type, token_endpoint_auth_method, name, description, logo_uri, status, registration_enabled, created_at, updated_at
`

type UpdateOIDCClientParams struct {
	Name                string             `db:"name"`
	Description         string             `db:"description"`
	LogoUri             *string            `db:"logo_uri"`
	Status              string             `db:"status"`
	RegistrationEnabled bool               `db:"registration_enabled"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	ID                  uuid.UUID          `db:"id"`
	ExpectedUpdatedAt   pgtype.Timestamptz `db:"expected_updated_at"`
}

func (q *Queries) UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, updateOIDCClient,
		arg.Name,
		arg.Description,
		arg.LogoUri,
		arg.Status,
		arg.RegistrationEnabled,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientType,
		&i.TokenEndpointAuthMethod,
		&i.Name,
		&i.Description,
		&i.LogoUri,
		&i.Status,
		&i.RegistrationEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
