// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consent.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentGrant = `-- name: CreateConsentGrant :one
INSERT INTO consent_grants (id, user_id, client_id, scopes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, client_id, scopes, created_at, updated_at
`

type CreateConsentGrantParams struct {
	ID        uuid.UUID          `db:"id"`
	UserID    uuid.UUID          `db:"user_id"`
	ClientID  uuid.UUID          `db:"client_id"`
	Scopes    []string           `db:"scopes"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) CreateConsentGrant(ctx context.Context, arg CreateConsentGrantParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, createConsentGrant,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConsentGrantByUserClient = `-- name: GetConsentGrantByUserClient :one
SELECT id, user_id, client_id, scopes, created_at, updated_at FROM consent_grants
WHERE user_id = $1 AND client_id = $2
`

type GetConsentGrantByUserClientParams struct {
	UserID   uuid.UUID `db:"user_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) GetConsentGrantByUserClient(ctx context.Context, arg GetConsentGrantByUserClientParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, getConsentGrantByUserClient, arg.UserID, arg.ClientID)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockConsentGrantByUserClient = `-- name: LockConsentGrantByUserClient :one
SELECT id, user_id, client_id, scopes, created_at, updated_at FROM consent_grants
WHERE user_id = $1 AND client_id = $2
FOR UPDATE
`

type LockConsentGrantByUserClientParams struct {
	UserID   uuid.UUID `db:"user_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) LockConsentGrantByUserClient(ctx context.Context, arg LockConsentGrantByUserClientParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, lockConsentGrantByUserClient, arg.UserID, arg.ClientID)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConsentGrantScopes = `-- name: UpdateConsentGrantScopes :one
UPDATE consent_grants
SET scopes = $1, updated_at = $2
WHERE id = $3
RETURNING id, user_id, client_id, scopes, created_at, updated_at
`

type UpdateConsentGrantScopesParams struct {
	Scopes    []string           `db:"scopes"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	ID        uuid.UUID          `db:"id"`
}

func (q *Queries) UpdateConsentGrantScopes(ctx context.Context, arg UpdateConsentGrantScopesParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, updateConsentGrantScopes, arg.Scopes, arg.UpdatedAt, arg.ID)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
