// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*)::bigint FROM users WHERE role = 'admin' AND status = 'active'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (
    user_id, credential_type, password_hash, created_at, updated_at
) VALUES (
    $1, 'password', $2,
    $3, $4
)
`

type CreateCredentialParams struct {
	UserID       uuid.UUID          `db:"user_id"`
	PasswordHash string             `db:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential,
		arg.UserID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, subject, username, username_normalized, display_name,
    email, email_normalized, email_verified, status, role,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12
)
RETURNING id, subject, username, username_normalized, display_name, email, email_normalized, email_verified, status, role, created_at, updated_at, last_login_at
`

type CreateUserParams struct {
	ID                 uuid.UUID          `db:"id"`
	Subject            string             `db:"subject"`
	Username           string             `db:"username"`
	UsernameNormalized string             `db:"username_normalized"`
	DisplayName        string             `db:"display_name"`
	Email              string             `db:"email"`
	EmailNormalized    string             `db:"email_normalized"`
	EmailVerified      bool               `db:"email_verified"`
	Status             string             `db:"status"`
	Role               string             `db:"role"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Subject,
		arg.Username,
		arg.UsernameNormalized,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.EmailVerified,
		arg.Status,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const findCredentialForLogin = `-- name: FindCredentialForLogin :one
SELECT
    u.id, u.subject, u.username, u.username_normalized, u.display_name,
    u.email, u.email_normalized, u.email_verified, u.status, u.role,
    u.created_at, u.updated_at, u.last_login_at,
    c.password_hash, c.updated_at AS credential_updated_at
FROM users AS u
JOIN credentials AS c ON c.user_id = u.id AND c.credential_type = 'password'
WHERE u.username_normalized = $1
   OR u.email_normalized = $1
ORDER BY (u.username_normalized = $1) DESC
LIMIT 1
`

type FindCredentialForLoginRow struct {
	ID                  uuid.UUID          `db:"id"`
	Subject             string             `db:"subject"`
	Username            string             `db:"username"`
	UsernameNormalized  string             `db:"username_normalized"`
	DisplayName         string             `db:"display_name"`
	Email               string             `db:"email"`
	EmailNormalized     string             `db:"email_normalized"`
	EmailVerified       bool               `db:"email_verified"`
	Status              string             `db:"status"`
	Role                string             `db:"role"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	LastLoginAt         pgtype.Timestamptz `db:"last_login_at"`
	PasswordHash        string             `db:"password_hash"`
	CredentialUpdatedAt pgtype.Timestamptz `db:"credential_updated_at"`
}

func (q *Queries) FindCredentialForLogin(ctx context.Context, identifier string) (FindCredentialForLoginRow, error) {
	row := q.db.QueryRow(ctx, findCredentialForLogin, identifier)
	var i FindCredentialForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.PasswordHash,
		&i.CredentialUpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, subject, username, username_normalized, display_name, email, email_normalized, email_verified, status, role, created_at, updated_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const hasAdmin = `-- name: HasAdmin :one
SELECT EXISTS (SELECT 1 FROM users WHERE role = 'admin')::boolean
`

func (q *Queries) HasAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdmin)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, subject, username, username_normalized, display_name, email, email_normalized, email_verified, status, role, created_at, updated_at, last_login_at
FROM users
WHERE (
        $1::text = ''
        OR username_normalized LIKE $1::text || '%'
        OR email_normalized LIKE $1::text || '%'
    )
  AND (
        $2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUsersParams struct {
	Search     string             `db:"search"`
	CursorTime pgtype.Timestamptz `db:"cursor_time"`
	CursorID   uuid.UUID          `db:"cursor_id"`
	PageLimit  int32              `db:"page_limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Username,
			&i.UsernameNormalized,
			&i.DisplayName,
			&i.Email,
			&i.EmailNormalized,
			&i.EmailVerified,
			&i.Status,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAdminSet = `-- name: LockAdminSet :exec
SELECT pg_advisory_xact_lock(780665710)
`

func (q *Queries) LockAdminSet(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAdminSet)
	return err
}

const lockLoginIdentifier = `-- name: LockLoginIdentifier :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 780665709))
`

func (q *Queries) LockLoginIdentifier(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, lockLoginIdentifier, identifier)
	return err
}

const lockUserByID = `-- name: LockUserByID :one
SELECT id, subject, username, username_normalized, display_name, email, email_normalized, email_verified, status, role, created_at, updated_at, last_login_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const loginIdentifierExists = `-- name: LoginIdentifierExists :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE username_normalized = $1
       OR email_normalized = $1
)::boolean
`

func (q *Queries) LoginIdentifierExists(ctx context.Context, identifier string) (bool, error) {
	row := q.db.QueryRow(ctx, loginIdentifierExists, identifier)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const loginIdentifierOwnedByOther = `-- name: LoginIdentifierOwnedByOther :one
SELECT EXISTS (
    SELECT 1 FROM users
    WHERE id <> $1
      AND (username_normalized = $2 OR email_normalized = $2)
)::boolean
`

type LoginIdentifierOwnedByOtherParams struct {
	ID         uuid.UUID `db:"id"`
	Identifier string    `db:"identifier"`
}

func (q *Queries) LoginIdentifierOwnedByOther(ctx context.Context, arg LoginIdentifierOwnedByOtherParams) (bool, error) {
	row := q.db.QueryRow(ctx, loginIdentifierOwnedByOther, arg.ID, arg.Identifier)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCredentialHash = `-- name: UpdateCredentialHash :exec
UPDATE credentials
SET password_hash = $1, updated_at = $2
WHERE user_id = $3 AND credential_type = 'password'
`

type UpdateCredentialHashParams struct {
	PasswordHash string             `db:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
	UserID       uuid.UUID          `db:"user_id"`
}

func (q *Queries) UpdateCredentialHash(ctx context.Context, arg UpdateCredentialHashParams) error {
	_, err := q.db.Exec(ctx, updateCredentialHash, arg.PasswordHash, arg.UpdatedAt, arg.UserID)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = $1, updated_at = GREATEST(updated_at, $1)
WHERE id = $2
`

type UpdateLastLoginParams struct {
	LastLoginAt pgtype.Timestamptz `db:"last_login_at"`
	ID          uuid.UUID          `db:"id"`
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    username = $1,
    username_normalized = $2,
    display_name = $3,
    email = $4,
    email_normalized = $5,
    status = $6,
    role = $7,
    updated_at = $8
WHERE id = $9 AND updated_at = $10
RETURNING id, subject, username, username_normalized, display_name, email, email_normalized, email_verified, status, role, created_at, updated_at, last_login_at
`

type UpdateUserParams struct {
	Username           string             `db:"username"`
	UsernameNormalized string             `db:"username_normalized"`
	DisplayName        string             `db:"display_name"`
	Email              string             `db:"email"`
	EmailNormalized    string             `db:"email_normalized"`
	Status             string             `db:"status"`
	Role               string             `db:"role"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
	ID                 uuid.UUID          `db:"id"`
	ExpectedUpdatedAt  pgtype.Timestamptz `db:"expected_updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.UsernameNormalized,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.Status,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.UsernameNormalized,
		&i.DisplayName,
		&i.Email,
		&i.EmailNormalized,
		&i.EmailVerified,
		&i.Status,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
