// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logout.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindPreConfirmLogoutTransaction = `-- name: BindPreConfirmLogoutTransaction :one
UPDATE logout_transactions
SET stage = 'bound_confirmable',
    csrf_hash = $1,
    user_id = $2,
    session_id = $3,
    session_binding_id = $4,
    bound_at = $5,
    post_logout_redirect_uri = CASE
        WHEN hint_subject IS NULL OR hint_subject = $6 THEN post_logout_redirect_uri
        ELSE NULL
    END,
    state_value = CASE
        WHEN hint_subject IS NULL OR hint_subject = $6 THEN state_value
        ELSE NULL
    END
WHERE id = $7
  AND stage = 'pre_confirm'
  AND consumed_at IS NULL
  AND expires_at > $5
RETURNING id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count
`

type BindPreConfirmLogoutTransactionParams struct {
	CsrfHash         []byte             `db:"csrf_hash"`
	UserID           *uuid.UUID         `db:"user_id"`
	SessionID        *uuid.UUID         `db:"session_id"`
	SessionBindingID *uuid.UUID         `db:"session_binding_id"`
	BoundAt          pgtype.Timestamptz `db:"bound_at"`
	Subject          *string            `db:"subject"`
	ID               uuid.UUID          `db:"id"`
}

func (q *Queries) BindPreConfirmLogoutTransaction(ctx context.Context, arg BindPreConfirmLogoutTransactionParams) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, bindPreConfirmLogoutTransaction,
		arg.CsrfHash,
		arg.UserID,
		arg.SessionID,
		arg.SessionBindingID,
		arg.BoundAt,
		arg.Subject,
		arg.ID,
	)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const cancelLogoutTransaction = `-- name: CancelLogoutTransaction :one
UPDATE logout_transactions
SET stage = 'canceled', csrf_hash = NULL, consumed_at = $1
WHERE id = $2
  AND stage = 'bound_confirmable'
  AND consumed_at IS NULL
RETURNING id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count
`

type CancelLogoutTransactionParams struct {
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
	ID         uuid.UUID          `db:"id"`
}

func (q *Queries) CancelLogoutTransaction(ctx context.Context, arg CancelLogoutTransactionParams) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, cancelLogoutTransaction, arg.ConsumedAt, arg.ID)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const confirmLogoutTransaction = `-- name: ConfirmLogoutTransaction :one
UPDATE logout_transactions
SET stage = 'confirmed', csrf_hash = NULL, consumed_at = $1
WHERE id = $2
  AND stage = 'bound_confirmable'
  AND consumed_at IS NULL
RETURNING id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count
`

type ConfirmLogoutTransactionParams struct {
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
	ID         uuid.UUID          `db:"id"`
}

func (q *Queries) ConfirmLogoutTransaction(ctx context.Context, arg ConfirmLogoutTransactionParams) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, confirmLogoutTransaction, arg.ConsumedAt, arg.ID)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const countLiveBoundLogoutTransactionsBySession = `-- name: CountLiveBoundLogoutTransactionsBySession :one
SELECT count(*)::bigint
FROM logout_transactions
WHERE session_id = $1
  AND stage = 'bound_confirmable'
  AND consumed_at IS NULL
  AND expires_at > $2
`

type CountLiveBoundLogoutTransactionsBySessionParams struct {
	SessionID *uuid.UUID         `db:"session_id"`
	Now       pgtype.Timestamptz `db:"now"`
}

func (q *Queries) CountLiveBoundLogoutTransactionsBySession(ctx context.Context, arg CountLiveBoundLogoutTransactionsBySessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLiveBoundLogoutTransactionsBySession, arg.SessionID, arg.Now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLogoutTransaction = `-- name: CreateLogoutTransaction :exec
INSERT INTO logout_transactions (
    id, lookup_hash, stage, verified_client_id, post_logout_redirect_uri,
    state_value, hint_subject, created_at, expires_at
) VALUES (
    $1, $2, 'pre_confirm', $3,
    $4, $5, $6,
    $7, $8
)
`

type CreateLogoutTransactionParams struct {
	ID                    uuid.UUID          `db:"id"`
	LookupHash            []byte             `db:"lookup_hash"`
	VerifiedClientID      *uuid.UUID         `db:"verified_client_id"`
	PostLogoutRedirectUri *string            `db:"post_logout_redirect_uri"`
	StateValue            *string            `db:"state_value"`
	HintSubject           *string            `db:"hint_subject"`
	CreatedAt             pgtype.Timestamptz `db:"created_at"`
	ExpiresAt             pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateLogoutTransaction(ctx context.Context, arg CreateLogoutTransactionParams) error {
	_, err := q.db.Exec(ctx, createLogoutTransaction,
		arg.ID,
		arg.LookupHash,
		arg.VerifiedClientID,
		arg.PostLogoutRedirectUri,
		arg.StateValue,
		arg.HintSubject,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteRetiredLogoutTransactions = `-- name: DeleteRetiredLogoutTransactions :execrows
WITH candidates AS (
    SELECT transactions.id
    FROM logout_transactions AS transactions
    WHERE (transactions.consumed_at IS NULL AND transactions.expires_at <= $1)
       OR (transactions.consumed_at IS NOT NULL AND transactions.consumed_at <= $2)
    ORDER BY COALESCE(transactions.consumed_at, transactions.expires_at), transactions.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
DELETE FROM logout_transactions AS transactions
USING candidates
WHERE transactions.id = candidates.id
`

type DeleteRetiredLogoutTransactionsParams struct {
	Now        pgtype.Timestamptz `db:"now"`
	Cutoff     pgtype.Timestamptz `db:"cutoff"`
	BatchLimit int32              `db:"batch_limit"`
}

func (q *Queries) DeleteRetiredLogoutTransactions(ctx context.Context, arg DeleteRetiredLogoutTransactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredLogoutTransactions, arg.Now, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLogoutTransactionByLookupHash = `-- name: GetLogoutTransactionByLookupHash :one
SELECT id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count FROM logout_transactions
WHERE lookup_hash = $1
`

func (q *Queries) GetLogoutTransactionByLookupHash(ctx context.Context, lookupHash []byte) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, getLogoutTransactionByLookupHash, lookupHash)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const incrementLogoutTransactionAttempt = `-- name: IncrementLogoutTransactionAttempt :one
UPDATE logout_transactions
SET attempt_count = attempt_count + 1
WHERE id = $1
  AND consumed_at IS NULL
  AND attempt_count < $2
RETURNING id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count
`

type IncrementLogoutTransactionAttemptParams struct {
	ID          uuid.UUID `db:"id"`
	MaxAttempts int16     `db:"max_attempts"`
}

func (q *Queries) IncrementLogoutTransactionAttempt(ctx context.Context, arg IncrementLogoutTransactionAttemptParams) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, incrementLogoutTransactionAttempt, arg.ID, arg.MaxAttempts)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const lockLiveAccessTokensByBinding = `-- name: LockLiveAccessTokensByBinding :many
SELECT id
FROM access_tokens
WHERE session_binding_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
ORDER BY id
FOR UPDATE
`

type LockLiveAccessTokensByBindingParams struct {
	SessionBindingID *uuid.UUID         `db:"session_binding_id"`
	Now              pgtype.Timestamptz `db:"now"`
}

func (q *Queries) LockLiveAccessTokensByBinding(ctx context.Context, arg LockLiveAccessTokensByBindingParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockLiveAccessTokensByBinding, arg.SessionBindingID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLiveAccessTokensByBindings = `-- name: LockLiveAccessTokensByBindings :many
SELECT id
FROM access_tokens
WHERE session_binding_id = ANY($1::uuid[])
  AND revoked_at IS NULL
  AND expires_at > $2
ORDER BY id
FOR UPDATE
`

type LockLiveAccessTokensByBindingsParams struct {
	SessionBindingIds []uuid.UUID        `db:"session_binding_ids"`
	Now               pgtype.Timestamptz `db:"now"`
}

func (q *Queries) LockLiveAccessTokensByBindings(ctx context.Context, arg LockLiveAccessTokensByBindingsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockLiveAccessTokensByBindings, arg.SessionBindingIds, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLoginSessionByID = `-- name: LockLoginSessionByID :one
SELECT id, user_id, token_hash, csrf_hash, csrf_expires_at, created_at, last_seen_at, authenticated_at, expires_at, idle_expires_at, revoked_at, revoke_reason, user_agent_hash, ip_prefix, session_binding_id FROM login_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockLoginSessionByID(ctx context.Context, id uuid.UUID) (LoginSession, error) {
	row := q.db.QueryRow(ctx, lockLoginSessionByID, id)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.CsrfExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AuthenticatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UserAgentHash,
		&i.IpPrefix,
		&i.SessionBindingID,
	)
	return i, err
}

const lockLogoutTransactionByLookupHash = `-- name: LockLogoutTransactionByLookupHash :one
SELECT id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count FROM logout_transactions
WHERE lookup_hash = $1
FOR UPDATE
`

func (q *Queries) LockLogoutTransactionByLookupHash(ctx context.Context, lookupHash []byte) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, lockLogoutTransactionByLookupHash, lookupHash)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const lockUnrevokedRefreshTokenFamiliesByBinding = `-- name: LockUnrevokedRefreshTokenFamiliesByBinding :many
SELECT id
FROM refresh_token_families
WHERE session_binding_id = $1
  AND revoked_at IS NULL
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockUnrevokedRefreshTokenFamiliesByBinding(ctx context.Context, sessionBindingID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockUnrevokedRefreshTokenFamiliesByBinding, sessionBindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUnrevokedRefreshTokenFamiliesByBindings = `-- name: LockUnrevokedRefreshTokenFamiliesByBindings :many
SELECT id
FROM refresh_token_families
WHERE session_binding_id = ANY($1::uuid[])
  AND revoked_at IS NULL
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockUnrevokedRefreshTokenFamiliesByBindings(ctx context.Context, sessionBindingIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockUnrevokedRefreshTokenFamiliesByBindings, sessionBindingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLiveAccessTokensByBinding = `-- name: RevokeLiveAccessTokensByBinding :execrows
UPDATE access_tokens
SET revoked_at = $1, revoke_reason = $2
WHERE session_binding_id = $3
  AND revoked_at IS NULL
  AND expires_at > $1
`

type RevokeLiveAccessTokensByBindingParams struct {
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason     *string            `db:"revoke_reason"`
	SessionBindingID *uuid.UUID         `db:"session_binding_id"`
}

func (q *Queries) RevokeLiveAccessTokensByBinding(ctx context.Context, arg RevokeLiveAccessTokensByBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveAccessTokensByBinding, arg.RevokedAt, arg.RevokeReason, arg.SessionBindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLiveAccessTokensByBindings = `-- name: RevokeLiveAccessTokensByBindings :execrows
UPDATE access_tokens
SET revoked_at = $1, revoke_reason = $2
WHERE session_binding_id = ANY($3::uuid[])
  AND revoked_at IS NULL
  AND expires_at > $1
`

type RevokeLiveAccessTokensByBindingsParams struct {
	RevokedAt         pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason      *string            `db:"revoke_reason"`
	SessionBindingIds []uuid.UUID        `db:"session_binding_ids"`
}

func (q *Queries) RevokeLiveAccessTokensByBindings(ctx context.Context, arg RevokeLiveAccessTokensByBindingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeLiveAccessTokensByBindings, arg.RevokedAt, arg.RevokeReason, arg.SessionBindingIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeLoginSessionBindingByID = `-- name: RevokeLoginSessionBindingByID :one
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = $2
WHERE id = $3
  AND revoked_at IS NULL
RETURNING id, user_id, token_hash, csrf_hash, csrf_expires_at, created_at, last_seen_at, authenticated_at, expires_at, idle_expires_at, revoked_at, revoke_reason, user_agent_hash, ip_prefix, session_binding_id
`

type RevokeLoginSessionBindingByIDParams struct {
	RevokedAt    pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason"`
	ID           uuid.UUID          `db:"id"`
}

func (q *Queries) RevokeLoginSessionBindingByID(ctx context.Context, arg RevokeLoginSessionBindingByIDParams) (LoginSession, error) {
	row := q.db.QueryRow(ctx, revokeLoginSessionBindingByID, arg.RevokedAt, arg.RevokeReason, arg.ID)
	var i LoginSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.CsrfExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AuthenticatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UserAgentHash,
		&i.IpPrefix,
		&i.SessionBindingID,
	)
	return i, err
}

const revokeRefreshTokenFamiliesByBinding = `-- name: RevokeRefreshTokenFamiliesByBinding :execrows
UPDATE refresh_token_families
SET revoked_at = $1, revoke_reason = $2
WHERE session_binding_id = $3
  AND revoked_at IS NULL
`

type RevokeRefreshTokenFamiliesByBindingParams struct {
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason     *string            `db:"revoke_reason"`
	SessionBindingID uuid.UUID          `db:"session_binding_id"`
}

func (q *Queries) RevokeRefreshTokenFamiliesByBinding(ctx context.Context, arg RevokeRefreshTokenFamiliesByBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamiliesByBinding, arg.RevokedAt, arg.RevokeReason, arg.SessionBindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamiliesByBindings = `-- name: RevokeRefreshTokenFamiliesByBindings :execrows
UPDATE refresh_token_families
SET revoked_at = $1, revoke_reason = $2
WHERE session_binding_id = ANY($3::uuid[])
  AND revoked_at IS NULL
`

type RevokeRefreshTokenFamiliesByBindingsParams struct {
	RevokedAt         pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason      *string            `db:"revoke_reason"`
	SessionBindingIds []uuid.UUID        `db:"session_binding_ids"`
}

func (q *Queries) RevokeRefreshTokenFamiliesByBindings(ctx context.Context, arg RevokeRefreshTokenFamiliesByBindingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamiliesByBindings, arg.RevokedAt, arg.RevokeReason, arg.SessionBindingIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateBoundLogoutTransactionCSRF = `-- name: RotateBoundLogoutTransactionCSRF :one
UPDATE logout_transactions
SET csrf_hash = $1
WHERE id = $2
  AND stage = 'bound_confirmable'
  AND consumed_at IS NULL
  AND expires_at > $3
  AND user_id = $4
  AND session_id = $5
  AND session_binding_id = $6
RETURNING id, lookup_hash, stage, csrf_hash, verified_client_id, post_logout_redirect_uri, state_value, hint_subject, user_id, session_id, session_binding_id, created_at, expires_at, bound_at, consumed_at, attempt_count
`

type RotateBoundLogoutTransactionCSRFParams struct {
	CsrfHash         []byte             `db:"csrf_hash"`
	ID               uuid.UUID          `db:"id"`
	Now              pgtype.Timestamptz `db:"now"`
	UserID           *uuid.UUID         `db:"user_id"`
	SessionID        *uuid.UUID         `db:"session_id"`
	SessionBindingID *uuid.UUID         `db:"session_binding_id"`
}

func (q *Queries) RotateBoundLogoutTransactionCSRF(ctx context.Context, arg RotateBoundLogoutTransactionCSRFParams) (LogoutTransaction, error) {
	row := q.db.QueryRow(ctx, rotateBoundLogoutTransactionCSRF,
		arg.CsrfHash,
		arg.ID,
		arg.Now,
		arg.UserID,
		arg.SessionID,
		arg.SessionBindingID,
	)
	var i LogoutTransaction
	err := row.Scan(
		&i.ID,
		&i.LookupHash,
		&i.Stage,
		&i.CsrfHash,
		&i.VerifiedClientID,
		&i.PostLogoutRedirectUri,
		&i.StateValue,
		&i.HintSubject,
		&i.UserID,
		&i.SessionID,
		&i.SessionBindingID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.BoundAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}
