// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeAuthTransaction(ctx context.Context, arg ConsumeAuthTransactionParams) (AuthTransaction, error)
	ConsumePreAuthSession(ctx context.Context, arg ConsumePreAuthSessionParams) (uuid.UUID, error)
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountActiveLoginSessions(ctx context.Context, now pgtype.Timestamptz) (int64, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateAuthTransaction(ctx context.Context, arg CreateAuthTransactionParams) error
	CreateCredential(ctx context.Context, arg CreateCredentialParams) error
	CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) error
	CreateOIDCClient(ctx context.Context, arg CreateOIDCClientParams) (OidcClient, error)
	CreateOIDCClientLogoutURI(ctx context.Context, arg CreateOIDCClientLogoutURIParams) error
	CreateOIDCClientRedirectURI(ctx context.Context, arg CreateOIDCClientRedirectURIParams) error
	CreateOIDCClientScope(ctx context.Context, arg CreateOIDCClientScopeParams) error
	CreateOIDCClientSecret(ctx context.Context, arg CreateOIDCClientSecretParams) error
	CreatePreAuthSession(ctx context.Context, arg CreatePreAuthSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredPreAuthSessions(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	DeleteOIDCClientLogoutURIs(ctx context.Context, clientID uuid.UUID) error
	DeleteOIDCClientRedirectURIs(ctx context.Context, clientID uuid.UUID) error
	DeleteOIDCClientScopes(ctx context.Context, clientID uuid.UUID) error
	DeleteRetiredAuthTransactions(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	DeleteRetiredLoginSessions(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	ExpireAuthTransactions(ctx context.Context, now pgtype.Timestamptz) ([]uuid.UUID, error)
	FindCredentialForLogin(ctx context.Context, identifier string) (FindCredentialForLoginRow, error)
	GetAuthTransactionByID(ctx context.Context, id uuid.UUID) (AuthTransaction, error)
	GetAuthTransactionByTokenHash(ctx context.Context, tokenHash []byte) (AuthTransaction, error)
	GetLoginSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetLoginSessionByTokenHashRow, error)
	GetOIDCClientByClientID(ctx context.Context, clientID string) (OidcClient, error)
	GetOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error)
	GetPreAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) (PreauthSession, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HasAdmin(ctx context.Context) (bool, error)
	ListActiveOIDCClientSecretHashes(ctx context.Context, clientID uuid.UUID) ([][]byte, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListLoginSessionsAdmin(ctx context.Context, arg ListLoginSessionsAdminParams) ([]ListLoginSessionsAdminRow, error)
	ListOIDCClientLogoutURIs(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListOIDCClientRedirectURIs(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListOIDCClientScopes(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListOIDCClients(ctx context.Context, arg ListOIDCClientsParams) ([]OidcClient, error)
	ListUserLoginSessions(ctx context.Context, arg ListUserLoginSessionsParams) ([]ListUserLoginSessionsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockAdminSet(ctx context.Context) error
	LockLoginIdentifier(ctx context.Context, identifier string) error
	LockOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error)
	LockUserByID(ctx context.Context, id uuid.UUID) (User, error)
	LoginIdentifierExists(ctx context.Context, identifier string) (bool, error)
	LoginIdentifierOwnedByOther(ctx context.Context, arg LoginIdentifierOwnedByOtherParams) (bool, error)
	Ping(ctx context.Context) (int32, error)
	RevokeActiveOIDCClientSecrets(ctx context.Context, arg RevokeActiveOIDCClientSecretsParams) ([]uuid.UUID, error)
	RevokeAllUserLoginSessions(ctx context.Context, arg RevokeAllUserLoginSessionsParams) ([]uuid.UUID, error)
	RevokeLoginSessionAdmin(ctx context.Context, arg RevokeLoginSessionAdminParams) (RevokeLoginSessionAdminRow, error)
	RevokeLoginSessionByHash(ctx context.Context, arg RevokeLoginSessionByHashParams) (RevokeLoginSessionByHashRow, error)
	RevokeLoginSessionForUser(ctx context.Context, arg RevokeLoginSessionForUserParams) (RevokeLoginSessionForUserRow, error)
	RevokeOtherLoginSessions(ctx context.Context, arg RevokeOtherLoginSessionsParams) ([]uuid.UUID, error)
	RotateLoginSessionCSRF(ctx context.Context, arg RotateLoginSessionCSRFParams) error
	TouchLoginSession(ctx context.Context, arg TouchLoginSessionParams) error
	UpdateCredentialHash(ctx context.Context, arg UpdateCredentialHashParams) error
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (OidcClient, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
