// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BindPreConfirmLogoutTransaction(ctx context.Context, arg BindPreConfirmLogoutTransactionParams) (LogoutTransaction, error)
	CancelLogoutTransaction(ctx context.Context, arg CancelLogoutTransactionParams) (LogoutTransaction, error)
	ConfirmLogoutTransaction(ctx context.Context, arg ConfirmLogoutTransactionParams) (LogoutTransaction, error)
	ConsumeAuthTransaction(ctx context.Context, arg ConsumeAuthTransactionParams) (AuthTransaction, error)
	ConsumeAuthorizationCode(ctx context.Context, arg ConsumeAuthorizationCodeParams) (AuthorizationCode, error)
	ConsumePreAuthSession(ctx context.Context, arg ConsumePreAuthSessionParams) (uuid.UUID, error)
	ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (RefreshToken, error)
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountActiveLoginSessions(ctx context.Context, now pgtype.Timestamptz) (int64, error)
	CountLiveBoundLogoutTransactionsBySession(ctx context.Context, arg CountLiveBoundLogoutTransactionsBySessionParams) (int64, error)
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateAuthTransaction(ctx context.Context, arg CreateAuthTransactionParams) error
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) error
	CreateConsentGrant(ctx context.Context, arg CreateConsentGrantParams) (ConsentGrant, error)
	CreateCredential(ctx context.Context, arg CreateCredentialParams) error
	CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) error
	CreateLogoutTransaction(ctx context.Context, arg CreateLogoutTransactionParams) error
	CreateOIDCClient(ctx context.Context, arg CreateOIDCClientParams) (OidcClient, error)
	CreateOIDCClientLogoutURI(ctx context.Context, arg CreateOIDCClientLogoutURIParams) error
	CreateOIDCClientRedirectURI(ctx context.Context, arg CreateOIDCClientRedirectURIParams) error
	CreateOIDCClientScope(ctx context.Context, arg CreateOIDCClientScopeParams) error
	CreateOIDCClientSecret(ctx context.Context, arg CreateOIDCClientSecretParams) error
	CreatePreAuthSession(ctx context.Context, arg CreatePreAuthSessionParams) error
	CreateRefreshAccessToken(ctx context.Context, arg CreateRefreshAccessTokenParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateRefreshTokenFamily(ctx context.Context, arg CreateRefreshTokenFamilyParams) (RefreshTokenFamily, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredPreAuthSessions(ctx context.Context, arg DeleteExpiredPreAuthSessionsParams) (int64, error)
	DeleteOIDCClientLogoutURIs(ctx context.Context, clientID uuid.UUID) error
	DeleteOIDCClientRedirectURIs(ctx context.Context, clientID uuid.UUID) error
	DeleteOIDCClientScopes(ctx context.Context, clientID uuid.UUID) error
	DeleteRetiredAccessTokens(ctx context.Context, arg DeleteRetiredAccessTokensParams) (int64, error)
	DeleteRetiredAuthTransactions(ctx context.Context, arg DeleteRetiredAuthTransactionsParams) (int64, error)
	DeleteRetiredAuthorizationCodes(ctx context.Context, arg DeleteRetiredAuthorizationCodesParams) (int64, error)
	DeleteRetiredLoginSessions(ctx context.Context, arg DeleteRetiredLoginSessionsParams) (int64, error)
	DeleteRetiredLogoutTransactions(ctx context.Context, arg DeleteRetiredLogoutTransactionsParams) (int64, error)
	DeleteRetiredRefreshTokenFamilies(ctx context.Context, arg DeleteRetiredRefreshTokenFamiliesParams) (int64, error)
	DeleteRetiredRefreshTokens(ctx context.Context, arg DeleteRetiredRefreshTokensParams) (int64, error)
	ExpireAuthTransactions(ctx context.Context, arg ExpireAuthTransactionsParams) ([]uuid.UUID, error)
	FindCredentialForLogin(ctx context.Context, identifier string) (FindCredentialForLoginRow, error)
	GetAccessTokenByJTIHash(ctx context.Context, jtiHash []byte) (AccessToken, error)
	GetAuthTransactionByID(ctx context.Context, id uuid.UUID) (AuthTransaction, error)
	GetAuthTransactionByTokenHash(ctx context.Context, tokenHash []byte) (AuthTransaction, error)
	GetAuthorizationCodeByHash(ctx context.Context, codeHash []byte) (AuthorizationCode, error)
	GetConsentGrantByUserClient(ctx context.Context, arg GetConsentGrantByUserClientParams) (ConsentGrant, error)
	GetLoginSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetLoginSessionByTokenHashRow, error)
	GetLogoutTransactionByLookupHash(ctx context.Context, lookupHash []byte) (LogoutTransaction, error)
	GetOIDCClientByClientID(ctx context.Context, clientID string) (OidcClient, error)
	GetOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error)
	GetPreAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) (PreauthSession, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetRefreshTokenFamilyByID(ctx context.Context, id uuid.UUID) (RefreshTokenFamily, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	HasAdmin(ctx context.Context) (bool, error)
	HasAuthorizationCodeExchangeRejection(ctx context.Context, authorizationCodeID *uuid.UUID) (bool, error)
	IncrementLogoutTransactionAttempt(ctx context.Context, arg IncrementLogoutTransactionAttemptParams) (LogoutTransaction, error)
	ListActiveOIDCClientSecretHashes(ctx context.Context, clientID uuid.UUID) ([][]byte, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListCurrentUserConsentGrants(ctx context.Context, arg ListCurrentUserConsentGrantsParams) ([]ListCurrentUserConsentGrantsRow, error)
	ListLoginSessionsAdmin(ctx context.Context, arg ListLoginSessionsAdminParams) ([]ListLoginSessionsAdminRow, error)
	ListOIDCClientLogoutURIs(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListOIDCClientRedirectURIs(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListOIDCClientScopes(ctx context.Context, clientID uuid.UUID) ([]string, error)
	ListOIDCClients(ctx context.Context, arg ListOIDCClientsParams) ([]OidcClient, error)
	ListUserLoginSessions(ctx context.Context, arg ListUserLoginSessionsParams) ([]ListUserLoginSessionsRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LockAccessTokenByID(ctx context.Context, id uuid.UUID) (AccessToken, error)
	LockActiveLoginSessionsByUser(ctx context.Context, userID uuid.UUID) ([]LoginSession, error)
	LockAdminSet(ctx context.Context) error
	LockAuthTransactionByID(ctx context.Context, id uuid.UUID) (AuthTransaction, error)
	LockAuthorizationCodeByHash(ctx context.Context, codeHash []byte) (AuthorizationCode, error)
	LockConsentGrantByUserClient(ctx context.Context, arg LockConsentGrantByUserClientParams) (ConsentGrant, error)
	LockLiveAccessTokensByBinding(ctx context.Context, arg LockLiveAccessTokensByBindingParams) ([]uuid.UUID, error)
	LockLiveAccessTokensByBindings(ctx context.Context, arg LockLiveAccessTokensByBindingsParams) ([]uuid.UUID, error)
	LockLiveAccessTokensByClient(ctx context.Context, arg LockLiveAccessTokensByClientParams) ([]uuid.UUID, error)
	LockLiveAccessTokensByGrant(ctx context.Context, arg LockLiveAccessTokensByGrantParams) ([]uuid.UUID, error)
	LockLiveAccessTokensByUser(ctx context.Context, arg LockLiveAccessTokensByUserParams) ([]uuid.UUID, error)
	LockLiveRefreshAccessTokensByClient(ctx context.Context, arg LockLiveRefreshAccessTokensByClientParams) ([]uuid.UUID, error)
	LockLoginIdentifier(ctx context.Context, identifier string) error
	LockLoginSessionByID(ctx context.Context, id uuid.UUID) (LoginSession, error)
	LockLoginSessionByTokenHash(ctx context.Context, tokenHash []byte) (LockLoginSessionByTokenHashRow, error)
	LockLogoutTransactionByLookupHash(ctx context.Context, lookupHash []byte) (LogoutTransaction, error)
	LockOIDCClientByClientID(ctx context.Context, clientID string) (OidcClient, error)
	LockOIDCClientByID(ctx context.Context, id uuid.UUID) (OidcClient, error)
	LockRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	LockRefreshTokenFamilyByID(ctx context.Context, id uuid.UUID) (RefreshTokenFamily, error)
	LockUnrevokedRefreshTokenFamiliesByBinding(ctx context.Context, sessionBindingID uuid.UUID) ([]uuid.UUID, error)
	LockUnrevokedRefreshTokenFamiliesByBindings(ctx context.Context, sessionBindingIds []uuid.UUID) ([]uuid.UUID, error)
	LockUnrevokedRefreshTokenFamiliesByClient(ctx context.Context, clientID uuid.UUID) ([]uuid.UUID, error)
	LockUnrevokedRefreshTokenFamiliesByGrant(ctx context.Context, consentGrantID uuid.UUID) ([]uuid.UUID, error)
	LockUnrevokedRefreshTokenFamiliesByUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	LockUserByID(ctx context.Context, id uuid.UUID) (User, error)
	LoginIdentifierExists(ctx context.Context, identifier string) (bool, error)
	LoginIdentifierOwnedByOther(ctx context.Context, arg LoginIdentifierOwnedByOtherParams) (bool, error)
	Ping(ctx context.Context) (int32, error)
	ReactivateConsentGrant(ctx context.Context, arg ReactivateConsentGrantParams) (ConsentGrant, error)
	RejectAuthTransaction(ctx context.Context, arg RejectAuthTransactionParams) (AuthTransaction, error)
	ReservePreAuthAttempt(ctx context.Context, arg ReservePreAuthAttemptParams) (PreauthSession, error)
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) (AccessToken, error)
	RevokeActiveOIDCClientSecrets(ctx context.Context, arg RevokeActiveOIDCClientSecretsParams) ([]uuid.UUID, error)
	RevokeAllUserLoginSessions(ctx context.Context, arg RevokeAllUserLoginSessionsParams) ([]uuid.UUID, error)
	RevokeConsentGrant(ctx context.Context, arg RevokeConsentGrantParams) (ConsentGrant, error)
	RevokeLiveAccessTokensByBinding(ctx context.Context, arg RevokeLiveAccessTokensByBindingParams) (int64, error)
	RevokeLiveAccessTokensByBindings(ctx context.Context, arg RevokeLiveAccessTokensByBindingsParams) (int64, error)
	RevokeLiveAccessTokensByClient(ctx context.Context, arg RevokeLiveAccessTokensByClientParams) (int64, error)
	RevokeLiveAccessTokensByFamily(ctx context.Context, arg RevokeLiveAccessTokensByFamilyParams) (int64, error)
	RevokeLiveAccessTokensByGrant(ctx context.Context, arg RevokeLiveAccessTokensByGrantParams) (int64, error)
	RevokeLiveAccessTokensByUser(ctx context.Context, arg RevokeLiveAccessTokensByUserParams) (int64, error)
	RevokeLiveRefreshAccessTokensByClient(ctx context.Context, arg RevokeLiveRefreshAccessTokensByClientParams) (int64, error)
	RevokeLoginSessionAdmin(ctx context.Context, arg RevokeLoginSessionAdminParams) (RevokeLoginSessionAdminRow, error)
	RevokeLoginSessionBindingByID(ctx context.Context, arg RevokeLoginSessionBindingByIDParams) (LoginSession, error)
	RevokeLoginSessionByHash(ctx context.Context, arg RevokeLoginSessionByHashParams) (RevokeLoginSessionByHashRow, error)
	RevokeLoginSessionByID(ctx context.Context, arg RevokeLoginSessionByIDParams) (RevokeLoginSessionByIDRow, error)
	RevokeLoginSessionForUser(ctx context.Context, arg RevokeLoginSessionForUserParams) (RevokeLoginSessionForUserRow, error)
	RevokeOtherLoginSessions(ctx context.Context, arg RevokeOtherLoginSessionsParams) ([]uuid.UUID, error)
	RevokeRefreshTokenFamiliesByBinding(ctx context.Context, arg RevokeRefreshTokenFamiliesByBindingParams) (int64, error)
	RevokeRefreshTokenFamiliesByBindings(ctx context.Context, arg RevokeRefreshTokenFamiliesByBindingsParams) (int64, error)
	RevokeRefreshTokenFamiliesByClient(ctx context.Context, arg RevokeRefreshTokenFamiliesByClientParams) (int64, error)
	RevokeRefreshTokenFamiliesByGrant(ctx context.Context, arg RevokeRefreshTokenFamiliesByGrantParams) ([]uuid.UUID, error)
	RevokeRefreshTokenFamiliesByUser(ctx context.Context, arg RevokeRefreshTokenFamiliesByUserParams) (int64, error)
	RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) (RefreshTokenFamily, error)
	RotateBoundLogoutTransactionCSRF(ctx context.Context, arg RotateBoundLogoutTransactionCSRFParams) (LogoutTransaction, error)
	RotateLoginSessionCSRF(ctx context.Context, arg RotateLoginSessionCSRFParams) error
	TouchLoginSession(ctx context.Context, arg TouchLoginSessionParams) error
	UpdateConsentGrantScopes(ctx context.Context, arg UpdateConsentGrantScopesParams) (ConsentGrant, error)
	UpdateCredentialHash(ctx context.Context, arg UpdateCredentialHashParams) error
	UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) error
	UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (OidcClient, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
