// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePreAuthSession = `-- name: ConsumePreAuthSession :one
UPDATE preauth_sessions
SET consumed_at = $1
WHERE id = $2
  AND consumed_at IS NULL
  AND expires_at > $1
RETURNING id
`

type ConsumePreAuthSessionParams struct {
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
	ID         uuid.UUID          `db:"id"`
}

func (q *Queries) ConsumePreAuthSession(ctx context.Context, arg ConsumePreAuthSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, consumePreAuthSession, arg.ConsumedAt, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countActiveLoginSessions = `-- name: CountActiveLoginSessions :one
SELECT count(*)::bigint
FROM login_sessions
WHERE revoked_at IS NULL
  AND expires_at > $1
  AND idle_expires_at > $1
`

func (q *Queries) CountActiveLoginSessions(ctx context.Context, now pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveLoginSessions, now)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLoginSession = `-- name: CreateLoginSession :exec
INSERT INTO login_sessions (
    id, user_id, session_binding_id, token_hash, csrf_hash, csrf_expires_at,
    created_at, last_seen_at, authenticated_at, expires_at, idle_expires_at,
    user_agent_hash, ip_prefix
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13
)
`

type CreateLoginSessionParams struct {
	ID               uuid.UUID          `db:"id"`
	UserID           uuid.UUID          `db:"user_id"`
	SessionBindingID uuid.UUID          `db:"session_binding_id"`
	TokenHash        []byte             `db:"token_hash"`
	CsrfHash         []byte             `db:"csrf_hash"`
	CsrfExpiresAt    pgtype.Timestamptz `db:"csrf_expires_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at"`
	AuthenticatedAt  pgtype.Timestamptz `db:"authenticated_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at"`
	IdleExpiresAt    pgtype.Timestamptz `db:"idle_expires_at"`
	UserAgentHash    []byte             `db:"user_agent_hash"`
	IpPrefix         *string            `db:"ip_prefix"`
}

func (q *Queries) CreateLoginSession(ctx context.Context, arg CreateLoginSessionParams) error {
	_, err := q.db.Exec(ctx, createLoginSession,
		arg.ID,
		arg.UserID,
		arg.SessionBindingID,
		arg.TokenHash,
		arg.CsrfHash,
		arg.CsrfExpiresAt,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.AuthenticatedAt,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.UserAgentHash,
		arg.IpPrefix,
	)
	return err
}

const createPreAuthSession = `-- name: CreatePreAuthSession :exec
INSERT INTO preauth_sessions (
    id, token_hash, csrf_hash, auth_transaction_id, created_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreatePreAuthSessionParams struct {
	ID                uuid.UUID          `db:"id"`
	TokenHash         []byte             `db:"token_hash"`
	CsrfHash          []byte             `db:"csrf_hash"`
	AuthTransactionID uuid.UUID          `db:"auth_transaction_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreatePreAuthSession(ctx context.Context, arg CreatePreAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createPreAuthSession,
		arg.ID,
		arg.TokenHash,
		arg.CsrfHash,
		arg.AuthTransactionID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredPreAuthSessions = `-- name: DeleteExpiredPreAuthSessions :execrows
WITH candidates AS (
    SELECT preauth.id
    FROM preauth_sessions AS preauth
    WHERE preauth.expires_at <= $1
       OR (preauth.consumed_at IS NOT NULL AND preauth.consumed_at <= $1)
    ORDER BY LEAST(preauth.expires_at, COALESCE(preauth.consumed_at, preauth.expires_at)), preauth.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM preauth_sessions AS sessions
USING candidates
WHERE sessions.id = candidates.id
`

type DeleteExpiredPreAuthSessionsParams struct {
	Cutoff     pgtype.Timestamptz `db:"cutoff"`
	BatchLimit int32              `db:"batch_limit"`
}

func (q *Queries) DeleteExpiredPreAuthSessions(ctx context.Context, arg DeleteExpiredPreAuthSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPreAuthSessions, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRetiredLoginSessions = `-- name: DeleteRetiredLoginSessions :execrows
WITH candidates AS (
    SELECT login.id
    FROM login_sessions AS login
    WHERE (login.revoked_at IS NOT NULL AND login.revoked_at <= $1)
       OR login.expires_at <= $1
       OR login.idle_expires_at <= $1
    ORDER BY LEAST(login.expires_at, login.idle_expires_at, COALESCE(login.revoked_at, login.expires_at)), login.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
DELETE FROM login_sessions AS sessions
USING candidates
WHERE sessions.id = candidates.id
`

type DeleteRetiredLoginSessionsParams struct {
	Cutoff     pgtype.Timestamptz `db:"cutoff"`
	BatchLimit int32              `db:"batch_limit"`
}

func (q *Queries) DeleteRetiredLoginSessions(ctx context.Context, arg DeleteRetiredLoginSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredLoginSessions, arg.Cutoff, arg.BatchLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLoginSessionByTokenHash = `-- name: GetLoginSessionByTokenHash :one
SELECT
    s.id, s.user_id, s.session_binding_id, s.token_hash, s.csrf_hash, s.csrf_expires_at,
    s.created_at, s.last_seen_at, s.authenticated_at, s.expires_at,
    s.idle_expires_at, s.revoked_at, s.revoke_reason,
    s.user_agent_hash, s.ip_prefix,
    u.subject, u.username, u.display_name, u.email, u.email_verified,
    u.status AS user_status, u.role AS user_role, u.created_at AS user_created_at,
    u.updated_at AS user_updated_at, u.last_login_at AS user_last_login_at,
    u.version AS user_version
FROM login_sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetLoginSessionByTokenHashRow struct {
	ID               uuid.UUID          `db:"id"`
	UserID           uuid.UUID          `db:"user_id"`
	SessionBindingID uuid.UUID          `db:"session_binding_id"`
	TokenHash        []byte             `db:"token_hash"`
	CsrfHash         []byte             `db:"csrf_hash"`
	CsrfExpiresAt    pgtype.Timestamptz `db:"csrf_expires_at"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	LastSeenAt       pgtype.Timestamptz `db:"last_seen_at"`
	AuthenticatedAt  pgtype.Timestamptz `db:"authenticated_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at"`
	IdleExpiresAt    pgtype.Timestamptz `db:"idle_expires_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason     *string            `db:"revoke_reason"`
	UserAgentHash    []byte             `db:"user_agent_hash"`
	IpPrefix         *string            `db:"ip_prefix"`
	Subject          string             `db:"subject"`
	Username         string             `db:"username"`
	DisplayName      string             `db:"display_name"`
	Email            string             `db:"email"`
	EmailVerified    bool               `db:"email_verified"`
	UserStatus       string             `db:"user_status"`
	UserRole         string             `db:"user_role"`
	UserCreatedAt    pgtype.Timestamptz `db:"user_created_at"`
	UserUpdatedAt    pgtype.Timestamptz `db:"user_updated_at"`
	UserLastLoginAt  pgtype.Timestamptz `db:"user_last_login_at"`
	UserVersion      int64              `db:"user_version"`
}

func (q *Queries) GetLoginSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetLoginSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getLoginSessionByTokenHash, tokenHash)
	var i GetLoginSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionBindingID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.CsrfExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AuthenticatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UserAgentHash,
		&i.IpPrefix,
		&i.Subject,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.EmailVerified,
		&i.UserStatus,
		&i.UserRole,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
		&i.UserLastLoginAt,
		&i.UserVersion,
	)
	return i, err
}

const getPreAuthSessionByTokenHash = `-- name: GetPreAuthSessionByTokenHash :one
SELECT id, token_hash, csrf_hash, auth_transaction_id, created_at, expires_at, consumed_at, attempt_count FROM preauth_sessions WHERE token_hash = $1
`

func (q *Queries) GetPreAuthSessionByTokenHash(ctx context.Context, tokenHash []byte) (PreauthSession, error) {
	row := q.db.QueryRow(ctx, getPreAuthSessionByTokenHash, tokenHash)
	var i PreauthSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.AuthTransactionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const listLoginSessionsAdmin = `-- name: ListLoginSessionsAdmin :many
SELECT s.id, s.user_id, s.created_at, s.last_seen_at, s.authenticated_at,
       s.expires_at, s.idle_expires_at, s.revoked_at, s.revoke_reason,
       s.ip_prefix, u.username, u.status AS user_status
FROM login_sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE (
        $1::timestamptz IS NULL
        OR (s.created_at, s.id) < ($1::timestamptz, $2::uuid)
      )
ORDER BY s.created_at DESC, s.id DESC
LIMIT $3
`

type ListLoginSessionsAdminParams struct {
	CursorTime pgtype.Timestamptz `db:"cursor_time"`
	CursorID   uuid.UUID          `db:"cursor_id"`
	PageLimit  int32              `db:"page_limit"`
}

type ListLoginSessionsAdminRow struct {
	ID              uuid.UUID          `db:"id"`
	UserID          uuid.UUID          `db:"user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at"`
	AuthenticatedAt pgtype.Timestamptz `db:"authenticated_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at"`
	IdleExpiresAt   pgtype.Timestamptz `db:"idle_expires_at"`
	RevokedAt       pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason    *string            `db:"revoke_reason"`
	IpPrefix        *string            `db:"ip_prefix"`
	Username        string             `db:"username"`
	UserStatus      string             `db:"user_status"`
}

func (q *Queries) ListLoginSessionsAdmin(ctx context.Context, arg ListLoginSessionsAdminParams) ([]ListLoginSessionsAdminRow, error) {
	rows, err := q.db.Query(ctx, listLoginSessionsAdmin, arg.CursorTime, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoginSessionsAdminRow{}
	for rows.Next() {
		var i ListLoginSessionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AuthenticatedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.IpPrefix,
			&i.Username,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLoginSessions = `-- name: ListUserLoginSessions :many
SELECT id, user_id, created_at, last_seen_at, authenticated_at, expires_at,
       idle_expires_at, revoked_at, revoke_reason, ip_prefix
FROM login_sessions
WHERE user_id = $1
  AND (
        $2::timestamptz IS NULL
        OR (created_at, id) < ($2::timestamptz, $3::uuid)
      )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUserLoginSessionsParams struct {
	UserID     uuid.UUID          `db:"user_id"`
	CursorTime pgtype.Timestamptz `db:"cursor_time"`
	CursorID   uuid.UUID          `db:"cursor_id"`
	PageLimit  int32              `db:"page_limit"`
}

type ListUserLoginSessionsRow struct {
	ID              uuid.UUID          `db:"id"`
	UserID          uuid.UUID          `db:"user_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at"`
	AuthenticatedAt pgtype.Timestamptz `db:"authenticated_at"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at"`
	IdleExpiresAt   pgtype.Timestamptz `db:"idle_expires_at"`
	RevokedAt       pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason    *string            `db:"revoke_reason"`
	IpPrefix        *string            `db:"ip_prefix"`
}

func (q *Queries) ListUserLoginSessions(ctx context.Context, arg ListUserLoginSessionsParams) ([]ListUserLoginSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserLoginSessions,
		arg.UserID,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserLoginSessionsRow{}
	for rows.Next() {
		var i ListUserLoginSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AuthenticatedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.IpPrefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveLoginSessionsByUser = `-- name: LockActiveLoginSessionsByUser :many
SELECT id, user_id, token_hash, csrf_hash, csrf_expires_at, created_at, last_seen_at, authenticated_at, expires_at, idle_expires_at, revoked_at, revoke_reason, user_agent_hash, ip_prefix, session_binding_id
FROM login_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockActiveLoginSessionsByUser(ctx context.Context, userID uuid.UUID) ([]LoginSession, error) {
	rows, err := q.db.Query(ctx, lockActiveLoginSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginSession{}
	for rows.Next() {
		var i LoginSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CsrfHash,
			&i.CsrfExpiresAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AuthenticatedAt,
			&i.ExpiresAt,
			&i.IdleExpiresAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.UserAgentHash,
			&i.IpPrefix,
			&i.SessionBindingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLoginSessionByTokenHash = `-- name: LockLoginSessionByTokenHash :one
SELECT id, user_id, session_binding_id, revoked_at, expires_at, idle_expires_at
FROM login_sessions
WHERE token_hash = $1
FOR UPDATE
`

type LockLoginSessionByTokenHashRow struct {
	ID               uuid.UUID          `db:"id"`
	UserID           uuid.UUID          `db:"user_id"`
	SessionBindingID uuid.UUID          `db:"session_binding_id"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at"`
	IdleExpiresAt    pgtype.Timestamptz `db:"idle_expires_at"`
}

func (q *Queries) LockLoginSessionByTokenHash(ctx context.Context, tokenHash []byte) (LockLoginSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, lockLoginSessionByTokenHash, tokenHash)
	var i LockLoginSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionBindingID,
		&i.RevokedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
	)
	return i, err
}

const reservePreAuthAttempt = `-- name: ReservePreAuthAttempt :one
UPDATE preauth_sessions
SET attempt_count = attempt_count + 1
WHERE id = $1
  AND consumed_at IS NULL
  AND expires_at > $2
  AND attempt_count < $3
RETURNING id, token_hash, csrf_hash, auth_transaction_id, created_at, expires_at, consumed_at, attempt_count
`

type ReservePreAuthAttemptParams struct {
	ID          uuid.UUID          `db:"id"`
	Now         pgtype.Timestamptz `db:"now"`
	MaxAttempts int16              `db:"max_attempts"`
}

func (q *Queries) ReservePreAuthAttempt(ctx context.Context, arg ReservePreAuthAttemptParams) (PreauthSession, error) {
	row := q.db.QueryRow(ctx, reservePreAuthAttempt, arg.ID, arg.Now, arg.MaxAttempts)
	var i PreauthSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.AuthTransactionID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.AttemptCount,
	)
	return i, err
}

const revokeAllUserLoginSessions = `-- name: RevokeAllUserLoginSessions :many
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = $2
WHERE user_id = $3 AND revoked_at IS NULL
RETURNING id
`

type RevokeAllUserLoginSessionsParams struct {
	RevokedAt    pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason"`
	UserID       uuid.UUID          `db:"user_id"`
}

func (q *Queries) RevokeAllUserLoginSessions(ctx context.Context, arg RevokeAllUserLoginSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllUserLoginSessions, arg.RevokedAt, arg.RevokeReason, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLoginSessionAdmin = `-- name: RevokeLoginSessionAdmin :one
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = $2
WHERE id = $3 AND revoked_at IS NULL
RETURNING id, user_id
`

type RevokeLoginSessionAdminParams struct {
	RevokedAt    pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason"`
	ID           uuid.UUID          `db:"id"`
}

type RevokeLoginSessionAdminRow struct {
	ID     uuid.UUID `db:"id"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) RevokeLoginSessionAdmin(ctx context.Context, arg RevokeLoginSessionAdminParams) (RevokeLoginSessionAdminRow, error) {
	row := q.db.QueryRow(ctx, revokeLoginSessionAdmin, arg.RevokedAt, arg.RevokeReason, arg.ID)
	var i RevokeLoginSessionAdminRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const revokeLoginSessionByHash = `-- name: RevokeLoginSessionByHash :one
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = $2
WHERE token_hash = $3 AND revoked_at IS NULL
RETURNING id, user_id
`

type RevokeLoginSessionByHashParams struct {
	RevokedAt    pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason"`
	TokenHash    []byte             `db:"token_hash"`
}

type RevokeLoginSessionByHashRow struct {
	ID     uuid.UUID `db:"id"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) RevokeLoginSessionByHash(ctx context.Context, arg RevokeLoginSessionByHashParams) (RevokeLoginSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, revokeLoginSessionByHash, arg.RevokedAt, arg.RevokeReason, arg.TokenHash)
	var i RevokeLoginSessionByHashRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const revokeLoginSessionByID = `-- name: RevokeLoginSessionByID :one
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = $2
WHERE id = $3 AND revoked_at IS NULL
RETURNING id, user_id, session_binding_id
`

type RevokeLoginSessionByIDParams struct {
	RevokedAt    pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason"`
	ID           uuid.UUID          `db:"id"`
}

type RevokeLoginSessionByIDRow struct {
	ID               uuid.UUID `db:"id"`
	UserID           uuid.UUID `db:"user_id"`
	SessionBindingID uuid.UUID `db:"session_binding_id"`
}

func (q *Queries) RevokeLoginSessionByID(ctx context.Context, arg RevokeLoginSessionByIDParams) (RevokeLoginSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, revokeLoginSessionByID, arg.RevokedAt, arg.RevokeReason, arg.ID)
	var i RevokeLoginSessionByIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.SessionBindingID)
	return i, err
}

const revokeLoginSessionForUser = `-- name: RevokeLoginSessionForUser :one
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = $2
WHERE id = $3 AND user_id = $4 AND revoked_at IS NULL
RETURNING id, user_id
`

type RevokeLoginSessionForUserParams struct {
	RevokedAt    pgtype.Timestamptz `db:"revoked_at"`
	RevokeReason *string            `db:"revoke_reason"`
	ID           uuid.UUID          `db:"id"`
	UserID       uuid.UUID          `db:"user_id"`
}

type RevokeLoginSessionForUserRow struct {
	ID     uuid.UUID `db:"id"`
	UserID uuid.UUID `db:"user_id"`
}

func (q *Queries) RevokeLoginSessionForUser(ctx context.Context, arg RevokeLoginSessionForUserParams) (RevokeLoginSessionForUserRow, error) {
	row := q.db.QueryRow(ctx, revokeLoginSessionForUser,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.ID,
		arg.UserID,
	)
	var i RevokeLoginSessionForUserRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const revokeOtherLoginSessions = `-- name: RevokeOtherLoginSessions :many
UPDATE login_sessions
SET revoked_at = $1, revoke_reason = 'others'
WHERE user_id = $2
  AND id <> $3
  AND revoked_at IS NULL
RETURNING id
`

type RevokeOtherLoginSessionsParams struct {
	RevokedAt        pgtype.Timestamptz `db:"revoked_at"`
	UserID           uuid.UUID          `db:"user_id"`
	CurrentSessionID uuid.UUID          `db:"current_session_id"`
}

func (q *Queries) RevokeOtherLoginSessions(ctx context.Context, arg RevokeOtherLoginSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeOtherLoginSessions, arg.RevokedAt, arg.UserID, arg.CurrentSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateLoginSessionCSRF = `-- name: RotateLoginSessionCSRF :exec
UPDATE login_sessions
SET csrf_hash = $1, csrf_expires_at = $2
WHERE id = $3 AND revoked_at IS NULL
`

type RotateLoginSessionCSRFParams struct {
	CsrfHash      []byte             `db:"csrf_hash"`
	CsrfExpiresAt pgtype.Timestamptz `db:"csrf_expires_at"`
	ID            uuid.UUID          `db:"id"`
}

func (q *Queries) RotateLoginSessionCSRF(ctx context.Context, arg RotateLoginSessionCSRFParams) error {
	_, err := q.db.Exec(ctx, rotateLoginSessionCSRF, arg.CsrfHash, arg.CsrfExpiresAt, arg.ID)
	return err
}

const touchLoginSession = `-- name: TouchLoginSession :exec
UPDATE login_sessions
SET last_seen_at = $1,
    idle_expires_at = LEAST(expires_at, $2)
WHERE id = $3
  AND revoked_at IS NULL
  AND expires_at > $1
  AND idle_expires_at > $1
`

type TouchLoginSessionParams struct {
	LastSeenAt    pgtype.Timestamptz `db:"last_seen_at"`
	IdleExpiresAt pgtype.Timestamptz `db:"idle_expires_at"`
	ID            uuid.UUID          `db:"id"`
}

func (q *Queries) TouchLoginSession(ctx context.Context, arg TouchLoginSessionParams) error {
	_, err := q.db.Exec(ctx, touchLoginSession, arg.LastSeenAt, arg.IdleExpiresAt, arg.ID)
	return err
}
