// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_tokens (
    id, jti_hash, authorization_code_id, consent_grant_id,
    user_id, client_id, scopes, issued_at, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9
)
`

type CreateAccessTokenParams struct {
	ID                  uuid.UUID          `db:"id"`
	JtiHash             []byte             `db:"jti_hash"`
	AuthorizationCodeID uuid.UUID          `db:"authorization_code_id"`
	ConsentGrantID      uuid.UUID          `db:"consent_grant_id"`
	UserID              uuid.UUID          `db:"user_id"`
	ClientID            uuid.UUID          `db:"client_id"`
	Scopes              []string           `db:"scopes"`
	IssuedAt            pgtype.Timestamptz `db:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `db:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAccessToken,
		arg.ID,
		arg.JtiHash,
		arg.AuthorizationCodeID,
		arg.ConsentGrantID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteRetiredAccessTokens = `-- name: DeleteRetiredAccessTokens :execrows
DELETE FROM access_tokens WHERE expires_at <= $1
`

func (q *Queries) DeleteRetiredAccessTokens(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredAccessTokens, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccessTokenByJTIHash = `-- name: GetAccessTokenByJTIHash :one
SELECT id, jti_hash, authorization_code_id, consent_grant_id, user_id, client_id, scopes, issued_at, expires_at FROM access_tokens WHERE jti_hash = $1
`

func (q *Queries) GetAccessTokenByJTIHash(ctx context.Context, jtiHash []byte) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByJTIHash, jtiHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.JtiHash,
		&i.AuthorizationCodeID,
		&i.ConsentGrantID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.IssuedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const hasAuthorizationCodeExchangeRejection = `-- name: HasAuthorizationCodeExchangeRejection :one
SELECT EXISTS (
    SELECT 1
    FROM audit_events
    WHERE event_type = 'authorization_code_exchange_rejected'
      AND target_type = 'authorization_code'
      AND target_id = $1
)
`

func (q *Queries) HasAuthorizationCodeExchangeRejection(ctx context.Context, authorizationCodeID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasAuthorizationCodeExchangeRejection, authorizationCodeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
